name: exchange_env
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - blinker>=1.8
  - click>=8.1
  - cycler>=0.12
  - flask[async]>=3.0
  - asgiref>=3.2
  - itsdangerous>=2.2
  - Jinja2>=3.1
  - joblib>=1.4
  - kiwisolver>=1.4
  - MarkupSafe>=2.1
  - neurokit2>=0.2
  - numpy>=1.26, <2
  - onnx>=1.16
  - onnxruntime>=1.18
  - packaging>=24
  - polars>=0.20
  - pyarrow>=16.1
  - pillow>=10.3
  - plotly>=5.20
  - pydicom>=2.4
  - pyparsing>=3.1
  - python-dateutil>=2.9
  - pytz>=2024.1
  - requests>=2.32
  - scikit-learn>=1.5
  - scipy>=1.12
  - six>=1.16
  - threadpoolctl>=3.5
  - Werkzeug>=3.0
  - tqdm>=4.66
  - flask-session>=0.8
  - redis[hiredis]>=5.0
  - gevent-websocket>=0.10
  - pytorch=2.2
  - onnx2torch>=1.5.13
  - pip
  - pip:
    - rlign
    - pysciebo>=1.1
    - onnxruntime_extensions>=0.11
    - protobuf>=5.27
    - celery[redis]>=5.4
    - matplotlib>=3.9
    - tsai>=0.3.9
    - gevent>=24.2
    - pandas>=2.2
    - uwsgi>=2.0